In [1]:
import pandas as pd

In [1]:
import numpy as np
def add_padding(mat):
    '''mat-> NumPy array
       output-> NumPy array is expected to be returned'''

    # YOUR CODE GOES HERE
    
    res=np.pad(array=mat,mode="constant",pad_width=1,constant_values=0)
    
    return res

In [2]:
import numpy as np
def seq(start, length, step):
    ''' start, length and step are in form of integers all representing the attributes as their names suggest
        output -> A numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    
    sequence = np.arange(start=start,stop=(length-1)*step,step=step)
    
    return sequence

In [3]:
import numpy as np
def rotate_img(mat):
    '''INPUT -> A 2d numpy array
       OUTPUT -> A 2d numpy array is expected to be returned'''
    np.rot90(mat,k=-1)

    # YOUR CODE GOES HERE
    
    # return OUTPUT

In [4]:
import numpy as np
def specific_elements(mat1,mat2,r1,r2,c1,c2):
    '''mat1,mat2 are the two 2d numpy array.
       r1,r2 are the start and end of rows indices
       c1,c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''
    
    # STEP1 CHECK whether matrix multiplication is possible
    noofcolumns=mat1.shape[1]
    noofrows=mat2.shape[0]
    if(noofcolumns != noofrows):
        return -1
    matmul_array=np.matmul(mat1,mat2)
    result=matmul_array[r1:r2,c1:c2] 

   
    
    return result

In [5]:
import numpy as np


def extract_subarray(arr):
    '''
    INPUT: arr -> 2D array
    
    OUPUT: result -> 2D array
    '''
    
    ### STEP1: Get the rows (2nd  to 4th row)
    
    row_array = arr[1:4,:]
    
    
    #### STEP 2: Get the last 3 cols from the row array
    
    cols_array = row_array[:,-3:]
    
    #### STEP3: Reverse the rows in cols array
    
    result = cols_array[::-1]
    

    return result

In [ ]:
import numpy as np

def calculate_mean_age(birds, age):
    '''
    INPUT: birds, age -> 1D array
    
    OUPUT: mean_age -> float variable
    '''
    
    mean_age = None
    
    ## STEP1. Create mask to get Crane birds from birds array
    mask = birds=="Cranes"
    
    ## STEP2. Get the age of crane birds
    
    crane_ages =age[mask]
    
    ## STEP 3. Calculate mean age of crane birds
    
    mean_age = np.mean(crane_ages)
    
    ## STEP 4. Round off the mean age to 2 decimal points
    
    mean_age = np.round(mean_age,2)
    
    
    
    return mean_age

In [ ]:
import numpy as np

def sort_birds(birds, age):
    '''
    INPUT: birds, age -> 1D numpy array
    
    OUTPUT: result -> sorted bird 1D array
    '''
    
    ## STEP 1 : Get the sorted index of age.
    
    sorted_age_index = np.argsort(age)
    
    ## STEP 2: Use the index from previous step to get sorted birds
    
    result = birds[sorted_age_index]
    
    return result

In [6]:
import numpy as np

def check_conditions(arr, k):
    '''
    INPUT: arr, k
    
    OUTPUT: result -> bool
    '''
    
    result = None
    
    ## STEP 1 : Create mask for the given condition
    
    mask = (arr%2==0) &(arr >k)
    
    ## STEP 2: Use logical function on mask
    
    result = np.all(mask)
    
    
    
    return result

In [7]:
import numpy as np

def split(arr, k):
    '''
    INPUT: arr, k
    
    OUTPUT: split_arr -> list of arrays
    '''
    
    split_arr = np.split(arr,k)
    
    ## CODE starts here
    
    
    
    return split_arr

In [8]:
def rearrange_image(data, num_splits):

    sections = np.split(data,k=2,axis=0)

    sections =[sections[-1]] +sections[:-1]

    return np.vstack(sections)

In [9]:

import pandas as pd

data = {
    'name': ['Mark', 'Ramilla', 'Deb', 'Laxman'],
    'profession': ['dev', 'mle', 'mle', 'hr'],
    'gender': ['male', 'female', 'male', 'male'],
    'age': [21, 20, 30, 27],
    'review': ['need improvement', 'Can be improved', 'Scope of improvement', 'Great'],
    'rating': [10, 5, 7, 9]
}

df = pd.DataFrame(data)
def specific_customers(df):
    ''' df is a dataframe with columns ['name', 'profession', 'gender', 'age', 'review', 'rating']
        Output -> A series with required names is expected to be returned'''
    # YOUR CODE GOES HERE
    
    # Select male professionals
    male_df=df[df["gender"]=="male"]
    filtered_df=male_df[male_df["age"]>=30]


    
    return filtered_df["name"]

In [11]:
data = {
    'name': ['Elon', 'Jeff', 'Bill', 'Falguni'],
    'gender': ['M', 'F', 'M', 'F'],
    'income': [53000, 28000, 25000, 44000]
}

df = pd.DataFrame(data)
highest_income=df["income"].max()
filtered_df=df[df["income"]==highest_income]
filtered_df["name"].iloc[0]

'Elon'

In [ ]:
import pandas as pd

data = {
    'city': ['Alaska', 'Texas', 'California', 'New York'],
    'area': [1723337, 695662, 423967, 783000],
    'population': [700000, 26448193, 38332521, 19651127]
}

df = pd.DataFrame(data)

In [12]:
import pandas as pd
def select_rows(df, r1, r2):
    '''
    input:
    df -> the dataframe provided to the function
    r1 -> the starting index of the rows to be selected
    r2 -> the ending index of the rows to be selected
    
    output:
    df_new -> the selected rows of the dataframe
    '''
    
    # Select the rows r1 to r2
    df_selected = df.iloc[r1:r2,:]
    
    # Select the columns "name" and "amt"
    df_new = df_selected.loc[:,["name","amt"]]
    
    return df_new

In [15]:
wide_df={
    "student_name":["Mani","gani","Devi","Narayana"],
    "math_scores":[40,50,60,70],
    "physics_score":[40,50,60,70],
    "chem_scores":[40,50,60,70]

}
df=pd.DataFrame(wide_df)
long_df=pd.melt(df,id_vars=["student_name"],value_vars=["math_scores","physics_score","chem_scores"],var_name="Melted Columns",value_name="Scores")
display(long_df)

   student_name Melted Columns  Scores
0          Mani    math_scores      40
1          gani    math_scores      50
2          Devi    math_scores      60
3      Narayana    math_scores      70
4          Mani  physics_score      40
5          gani  physics_score      50
6          Devi  physics_score      60
7      Narayana  physics_score      70
8          Mani    chem_scores      40
9          gani    chem_scores      50
10         Devi    chem_scores      60
11     Narayana    chem_scores      70

In [20]:
df_long = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob'],
    'Subject': ['Math', 'Math', 'Physics', 'Physics', 'Chemistry', 'Chemistry'],
    'Score': [95, 82, 89, 90, 92, 78]
})
wide_df2=pd.pivot_table(df_long,index="Student",columns="Subject",values="Score",aggfunc="mean")
display(wide_df2)

Subject  Chemistry  Math  Physics
Student
Alice         92.0  95.0     89.0
Bob           78.0  82.0     90.0

In [21]:
credit_score=[520,620,720,820,920]
bins=[500,600,700,800,900]
labels=["verylow","low","medium","high"]
pd.cut(credit_score,bins=bins,labels=labels)

['verylow', 'low', 'medium', 'high', NaN]
Categories (4, str): ['verylow' < 'low' < 'medium' < 'high']

In [ ]:
def solve(df):
    df["Date"]=pd.to_datetime(df["Date"])
    df["Month"]=df["Date"].dt.month_name()
    month_count=df["Month"].value_counts().sort_index()
    highestfreq=month_count.max()
    freq_month=month_count[month_count==highestfreq].index[0]
    new_df=df[df["Month"]==freq_month]
    return pd.Series([freq_month[:3].upper(),new_df["chem"].mean()])

In [23]:
from scipy.stats import binom
n=5
p=0.6
x=3
probablity=binom.pmf(x,n,p)
print(probablity)

0.3455999999999997

In [24]:
from scipy.stats import norm
mean=119
sd=13.1
speed=norm.ppf(0.90,mean,sd)
display(speed)

np.float64(135.78832550863427)